# Generated by Django 5.1.15 on 2026-08-26 08:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(help_text="uid d'origine MariaDB", unique=True)),
                ('code', models.CharField(help_text='Code pays (souvent ISO 3166-1 alpha-2)', max_length=10, unique=True)),
                ('libelle_fr', models.CharField(max_length=256)),
                ('libelle_en', models.CharField(max_length=256)),
                ('box_so_lat', models.FloatField(blank=True, null=True)),
                ('box_so_long', models.FloatField(blank=True, null=True)),
                ('box_ne_lat', models.FloatField(blank=True, null=True)),
                ('box_ne_long', models.FloatField(blank=True, null=True)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('flash_fr', models.TextField(blank=True, null=True)),
                ('flash_en', models.TextField(blank=True, null=True)),
                ('risques_synthese', models.JSONField(blank=True, default=dict, help_text='Champs hérités tels quels de la base historique (CHIK, PALU, FJ_*, ZIKA...)')),
            ],
        ),
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('libelle_fr', models.CharField(max_length=256)),
                ('libelle_en', models.CharField(max_length=256)),
                ('nature_du_risque_fr', models.TextField(help_text='Description du mécanisme du risque (ex. mode de transmission)')),
                ('nature_du_risque_en', models.TextField()),
                ('ordre', models.IntegerField(blank=True, help_text="Ordre d'affichage suggéré", null=True)),
                ('couleur_legende', models.CharField(blank=True, max_length=30, null=True)),
                ('legende_fr', models.CharField(blank=True, max_length=100)),
                ('legende_en', models.CharField(blank=True, max_length=100)),
                ('lien_fr', models.URLField(blank=True, null=True)),
                ('lien_en', models.URLField(blank=True, null=True)),
                ('cat_zones_saines_fr', models.TextField(blank=True)),
                ('cat_zones_saines_en', models.TextField(blank=True)),
                ('legende_zones_saines_fr', models.CharField(blank=True, max_length=256)),
                ('legende_zones_saines_en', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ConduiteATenir',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nature_du_risque_fr', models.TextField(help_text='Description du niveau/contexte de risque pour cette variante')),
                ('nature_du_risque_en', models.TextField()),
                ('recommandation_fr', models.TextField(blank=True, help_text="Conduite à tenir affichée à l'utilisateur (texte validé médical)")),
                ('recommandation_en', models.TextField(blank=True)),
                ('legende_fr', models.CharField(blank=True, max_length=256)),
                ('legende_en', models.CharField(blank=True, max_length=256)),
                ('couleur', models.CharField(blank=True, max_length=30, null=True)),
                ('risque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conduites', to='risks.risque')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(help_text="id d'origine dans la base MariaDB historique, conservé pour traçabilité", unique=True)),
                ('nom', models.CharField(max_length=256)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, help_text="Nul pour les zones sans géométrie exploitable à l'import (cf. note)", null=True, srid=4326)),
                ('note', models.CharField(blank=True, help_text="Anomalie constatée à l'import (géométrie manquante ou tronquée)", max_length=256)),
            ],
            options={
                'indexes': [models.Index(fields=['source_id'], name='risks_zone_source__3b9a24_idx')],
            },
        ),
        migrations.CreateModel(
            name='ZoneSaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(unique=True)),
                ('libelle_fr', models.CharField(max_length=256)),
                ('libelle_en', models.CharField(blank=True, max_length=256, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('conduite_a_tenir', models.ForeignKey(blank=True, help_text="Risque neutralisé en ce point ; nul si l'exception n'est pas encore renseignée", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_saines', to='risks.conduiteatenir')),
                ('pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_saines', to='risks.pays')),
                ('zone', models.ForeignKey(blank=True, help_text='Zone endémique dans laquelle ce point fait exception', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_saines', to='risks.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Endemie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Nul = période en cours (pas de fin connue)', null=True)),
                ('conduite_a_tenir', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='endemies', to='risks.conduiteatenir')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endemies', to='risks.zone')),
            ],
            options={
                'indexes': [models.Index(fields=['zone', 'date_fin'], name='risks_endem_zone_id_1817c7_idx'), models.Index(fields=['conduite_a_tenir'], name='risks_endem_conduit_210725_idx')],
            },
        ),
    ]
