# Generated by Django 5.1.15 on 2026-08-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conduiteatenir',
            name='legende_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conduiteatenir',
            name='legende_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pays',
            name='code',
            field=models.CharField(help_text='Code pays (souvent ISO 3166-1 alpha-2 ; quelques entrées historiques utilisent un libellé complet, ex. Galápagos)', max_length=30, unique=True),
        ),
    ]
