# Generated by Django 5.1.15 on 2026-08-26 20:33

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_alter_conduiteatenir_legende_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endemie',
            name='zone_exclue',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, help_text="Zone géographique où ce risque précis est absent malgré la Zone englobante (ex. une ville épargnée par le paludisme). Remplace l'ancien mécanisme ZoneSaine : porté ici plutôt que sur Zone elle-même, car une même Zone peut porter plusieurs risques et l'exclusion ne concerne généralement qu'un seul d'entre eux.", null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='zone',
            name='pays',
            field=models.ForeignKey(blank=True, help_text="Renseigné uniquement pour les Zone qui portent la frontière administrative d'un pays (issues des anciens placeholders 'zone_XX') — nul pour les zones de risque écologiques.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_frontiere', to='risks.pays'),
        ),
        migrations.DeleteModel(
            name='ZoneSaine',
        ),
    ]
