# Generated by Django 5.1.15 on 2026-09-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0005_conduiteatenir_facteurs_de_risque'),
    ]

    operations = [
        migrations.AddField(
            model_name='risque',
            name='vaccin_disponible',
            field=models.BooleanField(default=False, help_text="Un vaccin existe-t-il pour ce risque ? Détermine si la couverture vaccinale peut être déclarée pour ce risque (cf. clients.VaccinationRisque). Faux notamment pour le paludisme (PAL), qui n'a pas de vaccin."),
        ),
    ]
