# Generated by Django 5.1.15 on 2026-09-08 19:40

import clients.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Format international (ex. +33...)', max_length=32, unique=True)),
                ('email_active', models.BooleanField(default=True)),
                ('push_active', models.BooleanField(default=True)),
                ('reminder_delay', models.CharField(choices=[('once', 'Une fois'), ('daily', 'Quotidien'), ('every_2_days', 'Tous les 2 jours'), ('weekly', 'Hebdomadaire')], default='daily', help_text="Délai de rappel en cas de séjour prolongé en zone à risque. Le cahier des charges prévoit une valeur par défaut suggérée selon le risque de la zone traversée — logique non encore implémentée (dépend du moteur de notification, cf. §6) : la valeur ci-dessus n'est pour l'instant qu'un défaut global à l'inscription, modifiable ensuite par l'utilisateur.", max_length=20)),
                ('subscription_status', models.CharField(choices=[('trial', 'Essai'), ('active', 'Actif'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='trial', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Mis à jour à chaque position reçue (cf. Position)', null=True)),
                ('consent_status', models.BooleanField(default=False, help_text='Consentement RGPD explicite donné au premier lancement')),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('api_token', models.CharField(default=clients.models.generate_api_token, editable=False, help_text="Jeton d'authentification de l'appli mobile (cf. clients.authentication)", max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plateforme', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to='clients.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=50)),
                ('ancienne_valeur', models.CharField(blank=True, max_length=100, null=True)),
                ('nouvelle_valeur', models.CharField(blank=True, max_length=100, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_changes', to='clients.utilisateur')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Horodatage serveur de réception (pas forcément celui du relevé GPS)')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='clients.utilisateur')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['utilisateur', '-received_at'], name='clients_pos_utilisa_89cfaf_idx')],
            },
        ),
    ]
