# Generated by Django 5.1.15 on 2026-09-09 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('risks', '0006_risque_vaccin_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRisque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.BooleanField(default=False, help_text='True = voyageur vacciné/protégé pour ce risque')),
                ('declared_at', models.DateTimeField(auto_now=True)),
                ('risque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations_utilisateurs', to='risks.risque')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='clients.utilisateur')),
            ],
            options={
                'verbose_name': 'Couverture vaccinale',
                'verbose_name_plural': 'Couvertures vaccinales',
                'constraints': [models.UniqueConstraint(fields=('utilisateur', 'risque'), name='une_entree_vaccination_par_risque')],
            },
        ),
    ]
