# Generated by Django 5.1.15 on 2026-09-11
# Rédigée à la main (pas de shell disponible sur cette machine pour lancer
# `makemigrations` — cf. clients/migrations/0001_initial.py et 0002 pour le
# style suivi). À vérifier avec `python manage.py makemigrations --check`
# avant déploiement.

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_vaccinationrisque'),
        ('risks', '0006_risque_vaccin_disponible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='last_seen_at',
            new_name='last_contact_at',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='last_contact_at',
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    'Horodatage seul (aucune position associée) du dernier check-in '
                    'reçu — sert uniquement à déclencher la relance "appli silencieuse" '
                    '(cf. saintex-spec-technique.md §8).'
                ),
                null=True,
            ),
        ),
        migrations.CreateModel(
            name='UserRiskZoneStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now_add=True, help_text="Première détection d'entrée dans cette zone à risque")),
                ('last_reminded_at', models.DateTimeField(blank=True, help_text='Dernier rappel envoyé pour cette zone (séjour prolongé) — sert à calculer le prochain rappel selon Utilisateur.reminder_delay (§8)', null=True)),
                ('endemie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs_actifs', to='risks.endemie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_actives', to='clients.utilisateur')),
            ],
            options={
                'verbose_name': 'Statut de zone à risque',
                'verbose_name_plural': 'Statuts de zone à risque',
            },
        ),
        migrations.AddConstraint(
            model_name='userriskzonestatus',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'endemie'), name='un_statut_par_utilisateur_et_endemie'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('alerte_zone', 'Alerte entrée en zone à risque'), ('rappel_zone', 'Rappel de séjour prolongé'), ('relance_silence', 'Relance appli silencieuse')], max_length=20)),
                ('position', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text="Position ayant déclenché la notification (alerte/rappel de zone). Nulle pour une relance_silence, qui ne porte par définition aucune position (c'est justement l'absence de contact qui la déclenche).", null=True, srid=4326)),
                ('message', models.TextField(help_text="Texte effectivement transmis, figé au moment de l'envoi")),
                ('destinataire', models.CharField(help_text='Email ou numéro de téléphone, figé au moment de l\'envoi', max_length=255)),
                ('canal', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push')], max_length=10)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échec')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('endemie', models.ForeignKey(blank=True, help_text='Renseigné pour alerte_zone/rappel_zone, nul pour relance_silence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='risks.endemie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clients.utilisateur')),
            ],
            options={
                'verbose_name': 'Journal de notification',
                'verbose_name_plural': 'Journal des notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['utilisateur', '-sent_at'], name='clients_not_utilisa_idx'),
        ),
    ]
