# Generated by Django 5.1.15 on 2026-09-11
# Rédigée à la main (cf. 0003_notification_engine_phase1.py) — supprime
# Position pour aligner le code sur saintex-spec-technique.md §7 (la
# position ne doit jamais être conservée en base, cf. décision Phase 2).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_notification_engine_phase1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
