# Generated by Django 5.1.15 on 2026-09-25
# Rédigée à la main (pas de shell disponible sur cette machine pour lancer
# `makemigrations` — cf. clients/migrations/0003_notification_engine_phase1.py
# pour le style suivi). À vérifier avec `python manage.py makemigrations
# --check` avant déploiement.
#
# Ajoute les champs de contrat à Utilisateur (cf. saintex-spec-technique.md
# §6/§7, décision réunion médicale : date de début fixée par l'utilisateur,
# la sélection de pays comme déclencheur d'activation est abandonnée) :
# contract_duration, purchased_at, contract_start_date.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='contract_duration',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Durée du contrat en mois, choisie à l'achat (1, 2, 3...)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='purchased_at',
            field=models.DateTimeField(blank=True, help_text="Horodatage de l'achat", null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='contract_start_date',
            field=models.DateField(
                blank=True,
                help_text=(
                    "Date de début du contrat, fixée par l'utilisateur lui-même à "
                    "l'achat (cf. saintex-spec-technique.md §6 — la sélection de pays "
                    "comme déclencheur d'activation a été abandonnée au profit d'une "
                    "date déclarée). Modifiable tant que cette date n'est pas encore "
                    "arrivée ; figée dès que le contrat démarre effectivement (cf. "
                    "contrat_demarre / valider_date_debut_contrat)."
                ),
                null=True,
            ),
        ),
    ]
