# Generated by Django 5.1.15 on 2026-09-25
# Rédigée à la main (pas de shell disponible sur cette machine pour lancer
# `makemigrations` — cf. clients/migrations/0005_contrat_date_debut.py pour
# le style suivi). À vérifier avec `python manage.py makemigrations --check`
# avant déploiement.
#
# Ajoute ParametreContrat (cf. saintex-spec-technique.md §6) : singleton
# admin-éditable pour l'horizon max de contract_start_date, remplaçant la
# constante CONTRACT_START_DATE_MAX_MONTHS_AHEAD en dur — le chiffre exact
# ("6 à 12 mois") n'étant pas arrêté au PV de réunion médicale, l'équipe
# doit pouvoir l'ajuster sans nouveau déploiement.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_contrat_date_debut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_max_mois', models.PositiveSmallIntegerField(
                    default=12,
                    help_text=(
                        "Horizon maximal (en mois) auquel un utilisateur peut fixer sa "
                        "date de début de contrat (cf. §6 — \"6 à 12 mois\", chiffre exact "
                        "non arrêté au PV de réunion)."
                    ),
                )),
            ],
            options={
                'verbose_name': 'Paramétrage du contrat',
                'verbose_name_plural': 'Paramétrage du contrat',
            },
        ),
    ]
