# Generated by Django 5.1.15 on 2026-09-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_voyage_en_famille'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='clients_not_utilisa_178d80_idx',
            old_name='clients_not_utilisa_idx',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='reminder_delay',
            field=models.CharField(choices=[('once', 'Une fois'), ('daily', 'Quotidien'), ('every_2_days', 'Tous les 2 jours'), ('weekly', 'Hebdomadaire')], default='daily', help_text="Délai de rappel en cas de séjour prolongé en zone à risque. Le cahier des charges prévoit une valeur par défaut suggérée selon le risque de la zone traversée — logique non encore implémentée (dépend du moteur de notification, cf. §8) : la valeur ci-dessus n'est pour l'instant qu'un défaut global à l'inscription, modifiable ensuite par l'utilisateur.", max_length=20),
        ),
    ]
